### ISSUE TITLE
Update cookiecutter to use new jobs framework

### ISSUE THREAD

**Issue by kdmccormick** [overhangio/cookiecutter-tutor-plugin#15]
Once https://github.com/overhangio/tutor/pull/738/ merges, update the cookiecutter to use `CLI_DO_INIT_TASKS` instead of `COMMANDS_INIT`.

**Comment by regisb** [comment]
You read my mind :)

**Comment by kdmccormick** [comment]
Fixed by https://github.com/overhangio/cookiecutter-tutor-plugin/pull/17 and https://github.com/overhangio/cookiecutter-tutor-plugin/pull/18
