### ISSUE TITLE
 Confirm that cookiecutter-tutor-plugin works with Palm

### ISSUE THREAD

**Issue by kdmccormick** [overhangio/cookiecutter-tutor-plugin#21]
Test steps:
* Check out Tutor's `palm` branch
* Run launch
* Use this repo to generate a new plugin
* Fill in the cookie-cut file: add a setting, override a setting, implement a patch, add a template, etc
* Install and enable the plugin
* tutor config save
* Confirm that the plugin affects the rendered env as expected
* tutor local start
* Confirm that the plugin affects the Open edX instance as expected

**Comment by arbrandes** [comment]
As luck would have it, I had to create a real plugin for Palm:

https://github.com/openedx/openedx-tutor-plugins/pull/4

...and I'm glad to report that AFAICT it worked perfectly. :)
