### ISSUE TITLE
Confirm that `cookiecutter-tutor-plugin` works with Quince

### ISSUE THREAD

**Issue by CodeWithEmad** [overhangio/cookiecutter-tutor-plugin#28]
I've created a basic plugin with templates and patches and installed it next to a quince setup. everything worked fine. 
@regisb @kdmccormick I want to know your opinion about having some sort of dummy plugin that uses all of tutor's features. we can always use that to make sure cookie-cutter works with tutor.

**Comment by regisb** [comment]
Would that plugin implement all of Tutor's hook [catalog](https://docs.tutor.overhang.io/reference/api/hooks/catalog.html)? That seems unnecessarily complex to me. 

In general, stacking more and more tests on top of a more project does not make me feel more comfortable about the project's safety. Adding more tests means that the CI infrastructure becomes harder to maintain, and not necessarily more reliability. 

In this context, I think that reactivity is preferrable to proactivity -- if that makes sense. In other words: I'm OK with a project that sometimes breaks, as long as we are able to fix it quickly.

**Comment by kdmccormick** [comment]
I think I am more pro-automated-testing than @regisb is, but I fully agree that adding new tests isn't a silver bullet for making a project safer.  It's worthwhile to think about automated tests in terms of their benefit vs. cost tradeoff. That is, the best test suites are ones that prevent bugs while also being easy to write, easy to fix, simple to run, non-brittle, and not huge consumer of CI minutes.

Maintainer time is a precious resource :) So, is the cookiecutter maintainer, I recommend you write a test-everything plugin if and only if you think it would save you time.

**Comment by regisb** [comment]
> So, is the cookiecutter maintainer, I recommend you write a test-everything plugin if and only if you think it would save you time.

That's the voice of reason.

**Comment by CodeWithEmad** [comment]
I understand and agree with your valid concerns about complexity and resource allocation. Thank you for presenting your thoughts. I'll close this PR for now.
