### ISSUE TITLE
cookiecutter-tutor-plugin codebase Python 3.12 upgrade

### ISSUE THREAD

**Issue by DawoudSheraz** [overhangio/cookiecutter-tutor-plugin#30]
Ensure cookiecutter-tutor-plugin codebase is compatible with Python 3.12

See https://github.com/overhangio/tutor/issues/1004 for the context.

**Comment by CodeWithEmad** [comment]
This is fixed in MR #29 -> https://github.com/overhangio/cookiecutter-tutor-plugin/pull/29/commits/bcfc62d53e15afcc200d220056ab147ea2042447
I'm waiting for your review there.

**Comment by DawoudSheraz** [comment]
> This is fixed in MR #29 -> [bcfc62d](https://github.com/overhangio/cookiecutter-tutor-plugin/commit/bcfc62d53e15afcc200d220056ab147ea2042447) I'm waiting for your review there.

Got it. But apart from pkg_resources removal, it would be good to see if there are any other items that need an upgrade to Py312. If not, its good.

**Comment by DawoudSheraz** [comment]
> There are no other parts in the cookie-cutter. it was just `pkg_resources` which is fixed in #29 .

Cool. Does this mean a new plugin that is created in Python 3.12 environment will work without any modification in latest tutor master, right?

**Comment by CodeWithEmad** [comment]
I just tested it with a python:3.12 image. the plugin was created, installed, and enabled successfully.
![Screenshot from 2024-02-26 18-48-26](https://github.com/overhangio/cookiecutter-tutor-plugin/assets/49523567/94ed4bda-87e7-4691-b9f1-68436cd44b0e)
Is there any further steps you have in mind?

**Comment by regisb** [comment]
I think we can close this as completed by #29.

**Comment by Danyal-Faheem** [comment]
Hi, shouldn't we also update the workflows here for python 3.12 as well?
https://github.com/overhangio/cookiecutter-tutor-plugin/blob/5d5241d198e57dd72cf254727bb5e7f8c3780f87/%7B%7B%20cookiecutter.package_name%20%7D%7D/.github/workflows/test.yml#L12-L15

Similar to what is being done in tutor-forum in this [PR](https://github.com/overhangio/tutor-forum/pull/32).

**Comment by DawoudSheraz** [comment]
Adding to @Danyal-Faheem 's point, it would be good to have both 3.8 and 3.12 workflows until the redwood release. It would ensure the changes being made are compatible with both Python versions.

**Comment by CodeWithEmad** [comment]
I have no objection to the idea, however, since it is just a cookiecutter and not a genuine plugin, I think we should provide only the essentials and allow the plugin developers to determine which versions they wish to support. I am interested in hearing @regisb's's viewpoint on this.

**Comment by DawoudSheraz** [comment]
@CodeWithEmad Hi, let's add CI checks and then close this out. I don't think there is any more action needed. CI checks are there only for backup that future changes (until Redwood) are compatible with 38 and 312. Thanks

**Comment by CodeWithEmad** [comment]
Agree. Have a look at https://github.com/overhangio/cookiecutter-tutor-plugin/pull/31

**Comment by CodeWithEmad** [comment]
I think we can close this as completed by #31
