### ISSUE TITLE
The v1 migration guide does not describe how to migrate custom commands

### ISSUE THREAD

**Issue by regisb** [overhangio/cookiecutter-tutor-plugin#5]
The need to migrate custom commands to v1 appeared while migrating the xqueue plugin: https://github.com/overhangio/tutor-xqueue/pull/8#discussion_r876745384

The migration guide to v1 should include instructions on how to migrate the `commands` object.

**Comment by regisb** [comment]
Sure thing! Just coordinate with the maintainer @kdmccormick :)

**Comment by kdmccormick** [comment]
Certainly @NeOneSoft , that contribution would be much appreciated!

**Comment by NeOneSoft** [comment]
Thank's a lot @kdmccormick !!. I already created this brief [PR](https://github.com/overhangio/cookiecutter-tutor-plugin/pull/8) to attend this issue. I'll be glad to attend your comments = D!!

**Comment by kdmccormick** [comment]
Was completed via https://github.com/overhangio/cookiecutter-tutor-plugin/pull/9 🎉
