### ISSUE TITLE
Include basic CI setup for new plugins

### ISSUE THREAD

**Issue by kdmccormick** [overhangio/cookiecutter-tutor-plugin#7]
Inspired by @fghaas 's work on https://github.com/overhangio/cookiecutter-tutor-plugin/pull/2. It would be good if the cookiecutter included a tox.ini and GHA workflow(s) for things like:
* linting
* style checking
* type checking
* testing that the plugin can be enabled and makes it through `tutor config save`
* testing custom CLI commands, if relevant

**Comment by fghaas** [comment]
@kdmccormick, feel free to pull from the `for-kyle` branch in my fork and work from there.

**Comment by kdmccormick** [comment]
Excellent, thank you!

**Comment by CodeWithEmad** [comment]
@kdmccormick should I close this one?

**Comment by CodeWithEmad** [comment]
Right now, all official tutor plugins have a simple `test.yml` which runs `make test`. if that's enough, I can include that in our cookiecutter.
@kdmccormick
